name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gcc-arm-none-eabi
      run: sudo apt-get install gcc-arm-none-eabi

    - name: Build with make
      run: cd jocktos && make
