version: '3'

services:
  build:
    image: jocktos:latest
    volumes:
      - ../:/app
    entrypoint: >
      /bin/sh -c "
        cd jocktos && make clean && make
      "
  qemu-emulator:
    image: jocktos:latest
    privileged: true
    ports:
      - "1234:1234"
    volumes:
      - ../:/app
    entrypoint: >
      /bin/sh -c "
        qemu-system-arm -machine olimex-stm32-h405 -kernel jocktos/build/main.elf -monitor none -nographic -serial stdio -s -S
      "
