name: Test Compile

on:
  push:
    paths:
      - 'jocktos/**'
    branches:
      - c_based_scheduler
  pull_request:
    branches:
      - c_based_scheduler
    paths:
      - 'jocktos/**'

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi

    - name: Build JOCKTOS debug
      run: cd jocktos && make debug

    - name: Build JOCKTOS Release
      run: cd jocktos && make release

   

      
