name: Test Compile

on:
  push:
    paths:
      - 'jocktos/**'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'jocktos/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi

    - name: Build jocktos
      run: cd jocktos && make
