name: Unit Tests

on:
  push:
    paths:
      - 'jocktos/**'
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'jocktos/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt-get update

    - name: Build All Tests
      run: cd jocktos/test && make

    - name: Bitmap Block Allocator
      run: cd jocktos/test/build && ./test_allocator.test
